package com.example.hongcheng.common.db.dao;

import android.database.sqlite.SQLiteDatabase;

import com.example.hongcheng.common.model.IpInfo;
import com.example.hongcheng.common.model.Place;

import java.util.Map;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ipInfoDaoConfig;
    private final DaoConfig placeDaoConfig;

    private final IpInfoDao ipInfoDao;
    private final PlaceDao placeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ipInfoDaoConfig = daoConfigMap.get(IpInfoDao.class).clone();
        ipInfoDaoConfig.initIdentityScope(type);

        placeDaoConfig = daoConfigMap.get(PlaceDao.class).clone();
        placeDaoConfig.initIdentityScope(type);

        ipInfoDao = new IpInfoDao(ipInfoDaoConfig, this);
        placeDao = new PlaceDao(placeDaoConfig, this);

        registerDao(IpInfo.class, ipInfoDao);
        registerDao(Place.class, placeDao);
    }
    
    public void clear() {
        ipInfoDaoConfig.getIdentityScope().clear();
        placeDaoConfig.getIdentityScope().clear();
    }

    public IpInfoDao getIpInfoDao() {
        return ipInfoDao;
    }

    public PlaceDao getPlaceDao() {
        return placeDao;
    }

}
